export const mockData = [
  {
    id: '1',
    name: 'Grand Royal Hotel',
    location: 'Downtown, NY',
    description: 'A 5-star hotel with luxury rooms and premium services.',
    image: require('../../Assests/Images/resturnant.png'),
  },
  {
    id: '2',
    name: 'Serenity Spa',
    location: 'Beachside, CA',
    description: 'Relax and unwind with a stunning ocean view.',
    image: require('../../Assests/Images/food2.png'),
  },
  {
    id: '3',
    name: 'Bella Italia',
    location: 'Central Park, NY',
    description: 'Authentic Italian cuisine with a modern twist.',
    image: require('../../Assests/Images/candle.png'),
  },
  {
    id: '4',
    name: 'Skyline Hotel',
    location: 'Downtown, NY',
    description: 'Luxury hotel with breathtaking skyline views.',
    image: require('../../Assests/Images/food.png'),
  },
  {
    id: '5',
    name: 'Tranquil Wellness Spa',
    location: 'Malibu, CA',
    description: 'A peaceful escape for body and mind relaxation.',
    image: require('../../Assests/Images/slider1.png'),
  },
  {
    id: '6',
    name: 'Tuscany Bites',
    location: 'Soho, NY',
    description: 'A taste of Italy with freshly made pasta and wine.',
    image: require('../../Assests/Images/food2.png'),
  },
  {
    id: '7',
    name: 'Sapphire Lounge',
    location: 'Brooklyn, NY',
    description: 'A cozy and elegant restaurant for fine dining.',
    image: require('../../Assests/Images/candle.png'),
  },
  {
    id: '8',
    name: 'The Prestige Hotel',
    location: 'Uptown, NY',
    description: 'Where comfort meets luxury in every stay.',
    image: require('../../Assests/Images/research.png'),
  },
  {
    id: '9',
    name: 'Blue Horizon Spa',
    location: 'Miami Beach, FL',
    description: 'Relaxing spa experience with tropical vibes.',
    image: require('../../Assests/Images/resturnant.png'),
  },
  {
    id: '10',
    name: 'La Piazza',
    location: 'Times Square, NY',
    description: 'Traditional Italian flavors in a lively atmosphere.',
    image: require('../../Assests/Images/candle.png'),
  },
];
